name: Automated API tests using Postman CLI

on: 
 workflow_dispatch:
 push:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "22742638-63a53f72-3917-497c-a558-b87c0e6457dd" -e "22742638-4d169f05-6dc9-4206-8f03-d46b4896ad0a"
      - name: logout
        run: postman logout ${{ secrets.POSTMAN_API_KEY }}
